"""Adding running_time column

Revision ID: 1998265ea176
Revises: c9c4e14136b4
Create Date: 2023-04-05 17:34:11.299334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1998265ea176'
down_revision = 'c9c4e14136b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('running_time', sa.Integer(), nullable=True))
        batch_op.alter_column('likes',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.alter_column('likes',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('running_time')

    # ### end Alembic commands ###
